name: Android Unit Tests

on:
  push:
    branches:
      - master

jobs:
  test-debug-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21.0.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21.0.8

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('Android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run unit tests with coverage
        working-directory: Android
        run: |
          chmod +x gradlew
          ./gradlew testDebugUnitTest
